Implementação de estrutura de class para o log
yantadeu/rancher-deploy-action pull request #4
Opened 2021-08-15 05:02 UTC by IvesCostaBr

fiz a criação de uma classe log com os metodos de exibição, em seguida fiz a implementação de uma unica instância na execução do programa na parte de exeção.

2021-08-27 20:09 UTC, yantadeu requested changes

2021-08-27 20:09 UTC, yantadeu commented on deploy_to_rancher.py
> +        return requests.get('{}/projects/c-hmjq4:p-4xx87/workloads'.format(self.rancher_url_api), auth=(self.access_key, self.secret_key))
Valor fixo precisa ser removido

2021-08-27 20:09 UTC, yantadeu commented on deploy_to_rancher.py
> +    print(deployment.rancher_auth())
É necessário manter esse print

2021-08-31 15:17 UTC, closed without merging

2021-08-31 15:19 UTC, IvesCostaBr commented on deploy_to_rancher.py
> +    print(deployment.rancher_auth())
Fala Yan, vou corrigir, estava dando uma olhada e esse log que coloquei não ta servindo muito, pois não tem como acompanhar o fluxo de todas as request vou pensar como implementar algo mais global